


// returned from downloadShift.scrapeShiftsFromCrewScheduler()
export const rows = [['5258357',
    'OS',
    'CAD',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 8:00:00 AM',
    '9/18/2019 8:00:00 PM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'False',
    '-',
    '-',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '028845 Madrid, C.',
    'OS',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '1',
    '0',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;'],
['5258375',
    'OS',
    'CAD',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 8:00:00 AM',
    '9/18/2019 8:00:00 PM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'False',
    '-',
    '-',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '028847 Maldonado, A.',
    'OS',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '1',
    '0',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;'],
['5257725',
    'X702 (09hr std crew)',
    'CAD',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 8:00:00 AM',
    '9/18/2019 5:00:00 PM',
    'NOTES: Use 319 truck and gear STUDENT/RIDER: NEMSA P Student (Trey Crouse)',
    'NEMSA P Student (Trey Crouse)',
    '&nbsp;',
    'True',
    'X702',
    'X702',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '015942 Waguespack, M.',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '023731 Reimer, J.',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257721',
    'XB718 (12hr Basic Crew)',
    'CAD',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 8:00:00 AM',
    '9/18/2019 8:00:00 PM',
    'NOTES: CS 2 gear',
    '&nbsp;',
    '&nbsp;',
    'True',
    'XB718',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '028491 Fernandez, H.',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '028894 Hendrickson, A.',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257733',
    'XB813 (12hr Basic Crew)',
    'CAD',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 8:00:00 AM',
    '9/18/2019 8:00:00 PM',
    'NOTES: Cov BLS gear',
    '&nbsp;',
    '&nbsp;',
    'True',
    'Xb813',
    'Xb813',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '014061 Breland, K.',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '029178 Billiot, A.',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257699',
    '99 (14hr std crew)',
    'IN',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 9:00:00 AM',
    '9/18/2019 9:00:00 PM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '099',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '026271 Lee, J.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '029174 Pittman, J.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257743',
    'XB811 (12hr Basic Crew)',
    'SLC',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 9:00:00 AM',
    '9/18/2019 9:00:00 PM',
    'NOTES: SLC BLS gear',
    '&nbsp;',
    '&nbsp;',
    'True',
    'xb811',
    'xb811',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '026690 Jones, J.',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '029177 Galland, M.',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257514',
    '92: Power E (12hr std crew)',
    'HA',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 10:00:00 AM',
    '9/18/2019 10:00:00 PM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '092',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '023794 Ragoonath, V.',
    '024294 Weber, C.',
    '1',
    'Dillon, Lee',
    '&nbsp;',
    '024521 Booth, S.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257521',
    '308 Even (12hr std crew)',
    'CAD',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 11:00:00 AM',
    '9/18/2019 11:00:00 PM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '308',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '021283 DiMaggio, C.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '028954 McClendon, A.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257542',
    '307 Day E (12hr std crew)',
    'SLC',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 12:00:00 PM',
    '9/19/2019 12:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '307',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '023909 Campbell, K.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '025230 Sanchez, J.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257914',
    '221 pm (12hr Sprint)',
    'SLC',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 4:00:00 PM',
    '9/19/2019 4:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '221',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '017816 Albritton, B.',
    'AE',
    'Potter, Amy',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '2',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;'],
['5257928',
    '226 Night Even (12hr Sprint)',
    'FOL',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 4:00:00 PM',
    '9/19/2019 4:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '226',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '015676 Silas, S.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '2',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;'],
['5257556',
    '304: Ngt E (12hr std crew)',
    'SLC',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 4:00:00 PM',
    '9/19/2019 4:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '304',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '014901 Webb, B.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '027624 Hover, H.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257563',
    '95:Ngt E (12hr std crew)',
    'HA',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 4:00:00 PM',
    '9/19/2019 4:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '095',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '023943 Edmonds, C.',
    '022524 Pounds, L.',
    'V',
    'Taylor, Stephanie',
    '&nbsp;',
    '026104 Sibley, R.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257580',
    '196: Night Odd (12hr std crew)',
    'SLC',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 5:00:00 PM',
    '9/19/2019 5:00:00 AM',
    'NOTES: CREW 3: 025784 White, M.; STUDENT/RIDER: M White MDCC #9',
    'M White MDCC #9',
    '&nbsp;',
    'True',
    '196',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '018313 Hopkins, K.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '026980 Robbins, A.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '025784 White, M.',
    'CP',
    'Jenkins, Markus',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '4',
    '0',
    '0',
    '0',
    '0',
    '&nbsp;'],
['5257852',
    '219 (12hr Sprint)',
    'CAD',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 5:00:00 PM',
    '9/19/2019 5:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '219',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '023793 Kenny, J.',
    '1',
    'Potter, Amy',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '2',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;'],
['5257591',
    '302: Ngt E (12hr std crew)',
    'CAD',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 5:00:00 PM',
    '9/19/2019 5:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '302',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '016827 Lopez, A.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '029194 Payne, K.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257605',
    '91: Night E (12hr std crew)',
    'AM',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 5:00:00 PM',
    '9/19/2019 5:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '091',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '025346 Dicicco, V.',
    '020021 King, M.',
    'V',
    'Taylor, Stephanie',
    '&nbsp;',
    '028017 Lambou, C.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5280780',
    'OS',
    'SLC',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 5:00:00 PM',
    '9/19/2019 5:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'False',
    '-',
    '-',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '029056 Hemphill, P.',
    'OS',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '1',
    '0',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;'],
['5257754',
    'X701 (12hr Basic Crew)',
    'SLC',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 5:00:00 PM',
    '9/19/2019 5:00:00 AM',
    'NOTES: SLC 1 gear and narcs',
    '&nbsp;',
    '&nbsp;',
    'True',
    'X701',
    'X701',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '012990 Taylor, N.',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '018828 Merz, D.',
    'AE',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257817',
    '98 (12hr std crew)',
    'IN',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 5:30:00 PM',
    '9/19/2019 5:30:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '098',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '022593 Robertson, D.',
    '1',
    'Taylor, Stephanie',
    '&nbsp;',
    '022593 Robertson, D.',
    '023205 Brock, A.',
    '1',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257866',
    '218 (12hr Sprint)',
    'HA',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 6:00:00 PM',
    '9/19/2019 6:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '218',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '2',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;'],
['5257942',
    '227 Night (12hr Sprint)',
    'HA',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 6:00:00 PM',
    '9/19/2019 6:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '227',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '2',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;'],
['5257633',
    '301: Ngt E (12hr std crew)',
    'CAD',
    '9/18/2019 12:00:00 AM',
    '9/18/2019 6:00:00 PM',
    '9/19/2019 6:00:00 AM',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    'True',
    '301',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '024914 Blackman, C.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '027242 Frank, J.',
    '018823 Ziegler, N.',
    '1',
    'Taylor, Stephanie',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;'],
['5257645',
    '96: Ngt O (12hr std crew)',
    'AM',
    '9/20/2019 12:00:00 AM',
    '9/20/2019 7:00:00 PM',
    '9/21/2019 7:00:00 AM',
    'NOTES: Use 94 truck and gear tonight',
    '&nbsp;',
    '&nbsp;',
    'True',
    '096',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '017813 Jackson, J.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '023415 Ricks, R.',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5259463',
    'P703',
    'AM',
    '9/20/2019 12:00:00 AM',
    '9/20/2019 7:00:00 PM',
    '9/20/2019 10:00:00 PM',
    'NOTES: East Feliciana vs Kentwoood @ KentwoodUse 96 truck and gear',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P703',
    'P703',
    'A',
    'Potter, Amy',
    '&nbsp;',
    '&nbsp;',
    '017189 Johnson, J.',
    'A',
    'Potter, Amy',
    '&nbsp;',
    '&nbsp;',
    '027968 Crouse, J.',
    'A',
    'Potter, Amy',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5259466',
    'P708',
    'HA',
    '9/20/2019 12:00:00 AM',
    '9/20/2019 7:00:00 PM',
    '9/20/2019 10:00:00 PM',
    'NOTES: Albany vs Springfield @ SpringfieldUse spare truck and HS 3 gear and narcs',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P708',
    'P708',
    'A',
    'Potter, Amy',
    '&nbsp;',
    '&nbsp;',
    '022887 Carranza, C.',
    'A',
    'Husser, Barbara',
    '&nbsp;',
    '&nbsp;',
    '023848 Charpentier, A.',
    'A',
    'Potter, Amy',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5259461',
    'P701',
    'SLC',
    '9/20/2019 12:00:00 AM',
    '9/20/2019 7:30:00 PM',
    '9/20/2019 10:30:00 PM',
    'NOTES: Harrison vs Slidell @ Slidell k/o 1900Use 199 truck and gear',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P701',
    'P701',
    'A',
    'Potter, Amy',
    '&nbsp;',
    '&nbsp;',
    '018742 Longman, B.',
    'A',
    'Silas, Stephan, 5676',
    '&nbsp;',
    '&nbsp;',
    '016312 Rousse, B.',
    'A',
    'Silas, Stephan, 5676',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5257860',
    '219 (12hr Sprint)',
    'CAD',
    '9/20/2019 12:00:00 AM',
    '9/20/2019 10:00:00 PM',
    '9/21/2019 5:00:00 AM',
    'NOTES: Used for FB game tonight',
    '&nbsp;',
    '&nbsp;',
    'True',
    '219',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '020206 Billiot, A.',
    '1',
    'Potter, Amy',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '2',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;']
    ,
['5204424',
    'Deadline: Kiwanas Tour De Tangi ',
    '&nbsp;',
    '9/21/2019 12:00:00 AM',
    '9/21/2019 6:30:00 AM',
    '9/21/2019 1:30:00 PM',
    'NOTES: Deadline: Kiwanas Tour De Tangi ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P701',
    'P701',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '&nbsp;',
    '022887 Carranza, C.',
    'B',
    'Albritton, Billy, 7816',
    '&nbsp;',
    '&nbsp;',
    '025394 Yates, J.',
    'B',
    'Albritton, Billy, 7816',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5204422',
    'Deadline: SLU vs. Lamar ',
    '&nbsp;',
    '9/21/2019 12:00:00 AM',
    '9/21/2019 6:00:00 PM',
    '9/21/2019 11:00:00 PM',
    'NOTES: Deadline: SLU vs. Lamar ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P702',
    'P702',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5204423',
    'Deadline: SLU vs. Lamar ',
    '&nbsp;',
    '9/21/2019 12:00:00 AM',
    '9/21/2019 6:00:00 PM',
    '9/21/2019 11:00:00 PM',
    'NOTES: Deadline: SLU vs. Lamar ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'G7',
    'G7',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '2',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;']
    ,
['5221621',
    'Deadline/Slidell: Mayor\'s Wild Game-Seafood-BBQ Co',
    '&nbsp;',
    '9/28/2019 12:00:00 AM',
    '9/28/2019 10:00:00 AM',
    '9/28/2019 4:00:00 PM',
    'NOTES: Deadline/Slidell: Mayor\'s Wild Game-Seafood-BBQ Cook-Off ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P704',
    'P704',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '&nbsp;',
    '022252 Jones, L.',
    'B',
    'Albritton, Billy, 7816',
    '&nbsp;',
    '&nbsp;',
    '026226 Scharwarth, A.',
    'B',
    'Albritton, Billy, 7816',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5240169',
    'Deadline: Old Navy Safety Fair ',
    '&nbsp;',
    '9/28/2019 12:00:00 AM',
    '9/28/2019 10:00:00 AM',
    '9/28/2019 4:00:00 PM',
    'NOTES: Deadline: Old Navy Safety Fair ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P703',
    'P703',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5259663',
    'Deadline/Donation: MS Society Bike Run ',
    '&nbsp;',
    '10/5/2019 12:00:00 AM',
    '10/5/2019 6:00:00 AM',
    '10/6/2019 6:00:00 PM',
    'NOTES: Deadline/Donation: MS Society Bike Run ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P704',
    'P704',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5259660',
    'Pd Standby: Folsom Thoroughbred ',
    '&nbsp;',
    '10/5/2019 12:00:00 AM',
    '10/5/2019 6:00:00 AM',
    '10/5/2019 10:00:00 AM',
    'NOTES: Pd Standby: Folsom Thoroughbred ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P702',
    'P702',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5259664',
    'Pd Standby: MS Society Bike Run ',
    '&nbsp;',
    '10/5/2019 12:00:00 AM',
    '10/5/2019 6:00:00 AM',
    '10/6/2019 4:00:00 PM',
    'NOTES: Pd Standby: MS Society Bike Run ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P703',
    'P703',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5259665',
    'Deadline/Donation: MS Society Bike Run ',
    '&nbsp;',
    '10/6/2019 12:00:00 AM',
    '10/6/2019 5:00:00 AM',
    '10/6/2019 4:00:00 PM',
    'NOTES: Deadline/Donation: MS Society Bike Run ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'H702',
    'H702',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5277579',
    'Deadline: Wooden Boat Festival ',
    '&nbsp;',
    '10/12/2019 12:00:00 AM',
    '10/12/2019 7:00:00 AM',
    '10/12/2019 10:00:00 PM',
    'NOTES: Deadline: Wooden Boat Festival ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P705',
    'P705',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5277580',
    'Deadline: Wooden Boat Festival ',
    '&nbsp;',
    '10/12/2019 12:00:00 AM',
    '10/12/2019 7:00:00 AM',
    '10/12/2019 10:00:00 PM',
    'NOTES: Deadline: Wooden Boat Festival ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P704',
    'P704',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5259666',
    'Deadline: SLU Vs. Icarnate Word ',
    '&nbsp;',
    '10/12/2019 12:00:00 AM',
    '10/12/2019 3:00:00 PM',
    '10/12/2019 8:21:00 PM',
    'NOTES: Deadline: SLU Vs. Icarnate Word ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P703',
    'P703',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5259789',
    'Gator: SLU vs. Incarnate Word ',
    '&nbsp;',
    '10/12/2019 12:00:00 AM',
    '10/12/2019 3:00:00 PM',
    '10/12/2019 8:21:00 PM',
    'NOTES: Gator: SLU vs. Incarnate Word ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'G7',
    'G7',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '2',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;']
    ,
['5277581',
    'Deadline: Wooden Boat Festival ',
    '&nbsp;',
    '10/13/2019 12:00:00 AM',
    '10/13/2019 7:00:00 AM',
    '10/13/2019 7:00:00 PM',
    'NOTES: Deadline: Wooden Boat Festival ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P703',
    'P703',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5277582',
    'Deadline: Wooden Boat Festival ',
    '&nbsp;',
    '10/13/2019 12:00:00 AM',
    '10/13/2019 7:00:00 AM',
    '10/13/2019 7:00:00 PM',
    'NOTES: Deadline: Wooden Boat Festival ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P704',
    'P704',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5259667',
    'Deadline/Slidell: Northshore on Tap ',
    '&nbsp;',
    '10/18/2019 12:00:00 AM',
    '10/18/2019 2:30:00 PM',
    '10/18/2019 9:00:00 PM',
    'NOTES: Deadline/Slidell: Northshore on Tap ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P702',
    'P702',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5265736',
    'Deadline/Slidell: St. Margret Mary Fair ',
    '&nbsp;',
    '10/19/2019 12:00:00 AM',
    '10/19/2019 10:00:00 AM',
    '10/19/2019 11:00:00 PM',
    'NOTES: Deadline/Slidell: St. Margret Mary Fair ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P703',
    'P703',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5259668',
    'Deadline: Honoring 1st Responders @ Amite Penecostal Church',
    '&nbsp;',
    '10/19/2019 12:00:00 AM',
    '10/19/2019 5:30:00 PM',
    '10/19/2019 8:00:00 PM',
    'NOTES: Deadline: Honoring 1st Responders @ Amite Penecostal Church. ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P702',
    'P702',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
    ,
['5265737',
    'Deadline/Slidell: St. Margret Mary Fair ',
    '&nbsp;',
    '10/20/2019 12:00:00 AM',
    '10/20/2019 10:00:00 AM',
    '10/20/2019 9:00:00 PM',
    'NOTES: Deadline/Slidell: St. Margret Mary Fair ',
    '&nbsp;',
    '&nbsp;',
    'True',
    'P703',
    'P703',
    '1',
    'Surkand, Kathleen',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '&nbsp;',
    '3',
    '0',
    '0',
    '0',
    '&nbsp;',
    '&nbsp;']
]